name: Build 3DS Homebrew

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup devkitPro
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.2/devkitpro-pacman.amd64.deb
        sudo dpkg -i devkitpro-pacman.amd64.deb
        sudo dkp-pacman -S --noconfirm 3ds-dev
    
    - name: Build project
      run: make
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 3ds-randomtitlepicker-build
        path: |
          *.3dsx
          *.elf
          *.smdh
