name: Build 3DS Homebrew

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup devkitPro
      run: |
        # Install devkitPro using the official method
        sudo apt-get update
        sudo apt-get install -y wget gnupg2
        wget -qO - https://pkg.devkitpro.org/devkitpro-keyring.gpg | sudo tee /usr/share/keyrings/devkitpro-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/devkitpro-keyring.gpg] https://pkg.devkitpro.org/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/devkitpro.list
        sudo apt-get update
        sudo apt-get install -y 3ds-dev
    
    - name: Build project
      run: make
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 3ds-randomtitlepicker-build
        path: |
          *.3dsx
          *.elf
          *.smdh
