name: Build 3DS Homebrew

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup devkitPro
      run: |
        # Install devkitPro using the official installation script
        sudo apt-get update
        sudo apt-get install -y wget curl
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        sudo dkp-pacman -Syu --noconfirm
        sudo dkp-pacman -S --noconfirm 3ds-dev
    
    - name: Build project
      run: make
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 3ds-randomtitlepicker-build
        path: |
          *.3dsx
          *.elf
          *.smdh
